name: "pushing to dockerhub"
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: "testing github actions"
        run: pwd
      - name: "testing printing"
        run: echo seif
        
      - name: "before printing the folder containts"
        run: ls
      - uses: actions/checkout@v3

      - name: "after printing the folder containts"
        run: ls      

      - name: "login to dockerhub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCUSERNAME }}
          password: ${{ secrets.DOCPASS }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: seifhatem/taskbyactions:latest

